### ISSUE TITLE
peform_runtime_config fails during Drupal startup

### ISSUE THREAD

**Issue by birkland** [jhu-idc/idc-isle-buildkit#10]
For static/cloud instances, [perform_runtime_config](https://github.com/jhu-idc/idc-isle-buildkit/blob/main/drupal/rootfs/etc/cont-init.d/99-custom-setup.sh#L160) fails due to errors like:
```
 [error]  Error: Cannot create references to/from string offsets in Drupal\Component\Utility\NestedArray::setValue() (line 155 of /var/www/drupal/web/core/lib/Drupal/Component/Utility/NestedArray.php) #0 /var/www/drupal/web/core/lib/Drupal/Core/Config/ConfigBase.php(192): Drupal\Component\Utility\NestedArray::setValue(Array, Array, NULL)
drupal_1      | #1 /var/www/drupal/web/core/lib/Drupal/Core/Config/Config.php(184): Drupal\Core\Config\ConfigBase->set('gemini_url.http...', NULL)
```

Fix the issue, or find an alternate way of performing the configuration (e.g. via settings.php).  As of #9 , this error will be permitted to occur without causing Drupal container termination as an exception to the rule.

**Comment by emetsger** [comment]
I think I see what's going in here... investigating.
