### ISSUE TITLE
Prevent confd from running every 5 minutes 

### ISSUE THREAD

**Issue by derekbelrose** [jhu-idc/idc-isle-buildkit#30]
Confd is currently configured to run constantly, resetting changes each 5 minutes.

There is a 'onetime' flag that can be appended to the command line to ensure it only runs once and dies.

According to the 'base' image, it is running continuously on boot:

https://github.com/jhu-idc/idc-isle-buildkit/blob/main/base/rootfs/etc/services.d/confd/run

**Comment by emetsger** [comment]
Addressed by #43
